import {Items} from '../types';

export const sections = <const>[
  'Africa',
  'Americas',
  'ArtandDesign',
  'Arts',
  'AsiaPacific',
  'Automobiles',
  'Baseball',
  'Books',
  'Business',
  'Climate',
  'CollegeBasketball',
  'CollegeFootball',
  'Dance',
  'Dealbook',
  'DiningandWine',
  'Economy',
  'Education',
  'EnergyEnvironment',
  'Europe',
  'FashionandStyle',
  'Golf',
  'Health',
  'Hockey',
  'HomePage',
  'Jobs',
  'Lens',
  'MediaandAdvertising',
  'MiddleEast',
  'MostEmailed',
  'MostShared',
  'MostViewed',
  'Movies',
  'Music',
  'NYRegion',
  'Obituaries',
  'PersonalTech',
  'Politics',
  'ProBasketball',
  'ProFootball',
  'RealEstate',
  'Science',
  'SmallBusiness',
  'Soccer',
  'Space',
  'Sports',
  'SundayBookReview',
  'Sunday-Review',
  'Technology',
  'Television',
  'Tennis',
  'Theater',
  'TMagazine',
  'Travel',
  'Upshot',
  'US',
  'Weddings',
  'Well',
  'World',
  'YourMoney',
];

export function getAllSections(): Items[] {
  let arr: Items[] = [];
  for (let i = 0; i < sections.length; i++) {
    arr.push({label: sections[i], value: sections[i]});
  }
  return arr;
}
